### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by verde79** [GlasgowCoderCollective/glasgowcodercollective.github.io#7]
Readme needs updated to reflect the info on site and fb.  Written in markdown

**Comment by L3gomancer** [comment]
There ya go :shipit:

**Comment by verde79** [comment]
Ed, I've just noticed there's only us mentioned in doing any work on the site, could you include Craig for working on the slack invite, and Alastair for keeping us doing things correctly/tidying up the old repo (however you want to word it!

**Comment by L3gomancer** [comment]
okay doke

**Comment by L3gomancer** [comment]
Submitted :neckbeard:

**Comment by verde79** [comment]
Merged!

**Comment by verde79** [comment]
Can you sort your markdown pretty please!?

**Comment by L3gomancer** [comment]
Hey I just noticed the wonky table before finding this issue about the wonky table 🙀 
Im literally doing the PR now
